name: Deploy to Vercel

on:
  push:
    branches:
      - main   # o la rama principal de tu repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
